---
- name: Create ansible cache directory
  file: path={{ ansible_cache_dir }} state=directory

- name: Install yum packages
  yum: name="{{ item }}" state=present
  with_items:
    - unzip

- name: Download Gradle {{gradle_version}}
  get_url: dest="{{ ansible_cache_dir }}" url=https://services.gradle.org/distributions/{{gradle_zipfile}}
  sudo: yes

- name: Extract Gradle
  shell: unzip "{{ ansible_cache_dir }}/{{gradle_zipfile}}" -d /usr/local/share/ creates=/usr/local/share/{{gradle_folder}}
  sudo: yes

- name: Add Gradle executable symlink to path
  shell: ln -s /usr/local/share/{{gradle_folder}}/bin/gradle /usr/local/bin/gradle creates=/usr/local/bin/gradle
  sudo: yes
